import { FC } from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import axios from 'axios'
import { useTranslation } from "next-i18next";
import Link from "next/link";
import { routes } from "@/utils/routes";
import { useRouter } from "next/router";

type Props = {
  questions: any[]
}

const MovePage: FC<Props> = ({ questions }) => {
  const { t } = useTranslation('move')
  const { locale } = useRouter()

  console.log('T_QUESTIONS:', questions)

  return (
    <>
      <Head>
        <title>Bolt homepage</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <h1 style={{ marginBottom: '2rem' }}>{t('title')}</h1>

      <ul>
        <li>
          <Link href={`${routes(locale).move}/test-1`}>{t('test-1')}</Link>
          <Link href={`${routes(locale).move}/test-2`}>{t('test-2')}</Link>
          <Link href={`${routes(locale).move}/test-3`}>{t('test-3')}</Link>
        </li>
      </ul>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {questions.map((q) =>
          <div key={q.id}>
            <h3>{q.setup}</h3>
            <p>{q.punchline}</p>
          </div>
        )}
      </div>
    </>
  )
}

export const getStaticProps = async ({ locale, ...rest }) => {
  let apiTestData = []
  try {
    const { data } = await axios.get('https://official-joke-api.appspot.com/jokes/programming/ten')
    apiTestData = data
  } catch (err) {
    apiTestData = []
  }

  return {
    props: {
      questions: apiTestData,
      ...(await serverSideTranslations(locale, ['move']))
    },
    revalidate: 60
  }
}

export default MovePage
